#! /bin/bash

echo "Welcome to nginx Installation"
echo "Choose your OS"
options=("CentOS" "Ubuntu")
select opt in "${options[@]}"
do
    case $opt in
        "CentOS")
            echo "you chose CentOS"
	    sudo yum install -y nginx
            ;;
        "Ubuntu")
            echo "you chose Ubuntu"
	    sudo apt-get install -y nginx
     	break
	;;
        *) echo "invalid option! Choose right option";;
    esac
done
